version: '3.4'

services:
  calculator:
    image: calculator-1.1
    build:
      context: .
      dockerfile: src/Calculator/Dockerfile
    depends_on:
     - redis

  rolls:
    image: rolls-1.1
    build:
      context: .
      dockerfile: src/Rolls/Dockerfile
    depends_on:
     - redis

  redis:
    image: redis:6.2-alpine
    ports:
      - 6379:6379


  presenter:
    image: presenter-1.1
    build:
      context: .
      dockerfile: src/Presenter/Dockerfile

